name: Upload Firefox Extension to AMO

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v1.7

jobs:
  sign-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: web-ext build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: youtubetime

      - name: Get release notes
        id: get_release_notes
        run: |
          RELEASE_NOTES=""
          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            RELEASE_NOTES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/$TAG_NAME" | jq -r .body)
            if [ "$RELEASE_NOTES" = "null" ] || [ -z "$RELEASE_NOTES" ]; then RELEASE_NOTES="Automated release for $TAG_NAME. See changelog or commit history for details."; fi
          fi
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create AMO metadata file
        run: |
          echo '{"version": {"release_notes": {"en-US": "'$(echo "${{ steps.get_release_notes.outputs.release_notes }}" | sed 's/"/\\"/g')'"}}}' > amo_metadata.json

      - name: web-ext sign (upload to AMO)
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: listed  # Change to 'unlisted' if you want private distribution
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          metaDataFile: amo_metadata.json

      - name: Upload signed extension
        uses: actions/upload-artifact@v4
        with:
          name: firefox-signed-extension
          path: ${{ steps.web-ext-sign.outputs.target }} 